Support Gradle configuration cache, small buildscript cleanups
BluSpring/Kilt pull request #107
Opened 2024-12-23 04:58 UTC by xtrm-en

Hope this isn't too opinionated, feel free to ask for changes!

2024-12-23 11:04 UTC, BluSpring requested changes
Left a review, I'm curious to know about the reasoning behind these.

2024-12-23 11:04 UTC, BluSpring commented on settings.gradle.kts
> +}
From previous experience, using the Foojay Resolvers alongside Fabric Loom would always result in some kind of weird mixture of errors within the buildscript. I would avoid using this unless there is very good reason to.

2024-12-23 11:04 UTC, BluSpring commented on build.gradle.kts
> +        notCompatibleWithConfigurationCache("This isn't called every build; to be fixed later")
The custom Kilt tasks are intentionally not called every build, they are used by me for determining how much I need to do in the codebase.

2024-12-23 11:04 UTC, BluSpring commented on settings.gradle.kts
> +}
Any specific reason as to why this has been moved here?

2024-12-23 16:34 UTC, xtrm-en commented on settings.gradle.kts
> +}
Haven't had any issues in the past, but considering the nature of the project maybe it'd be best not to risk it

2024-12-23 16:34 UTC, xtrm-en commented on build.gradle.kts
> +        notCompatibleWithConfigurationCache("This isn't called every build; to be fixed later")
Yup, maybe the "to be fixed later" phrasing wasn't useful, it's just to mark them as intentionnally not compatible to not trigger build failures

2024-12-23 16:35 UTC, xtrm-en commented on settings.gradle.kts
> +}
That was just to unclutter the main buildscript and share them throughout subprojects (for potential modularization), this is mainly preference tho

2024-12-23 16:40 UTC, BluSpring commented on settings.gradle.kts
> +}
Please remove the plugin whenever you can.

2024-12-23 16:41 UTC, BluSpring commented on build.gradle.kts
> +        notCompatibleWithConfigurationCache("This isn't called every build; to be fixed later")
I would recommend changing the text to something else, maybe something along the lines of "Must not be cached".

2024-12-23 16:41 UTC, BluSpring commented on settings.gradle.kts
> +}
I'll allow it.

2024-12-24 13:43 UTC, BluSpring approved these changes

2024-12-24 13:44 UTC, merged

2024-12-30 20:08 UTC, BluSpring commented
PR has been reverted due to there being a lot of issues with the buildscript, especially in launching the game. That one's on me, I didn't have time to check on it before merging, will actually spend time to try out the PRs next time.

2024-12-31 03:06 UTC, xtrm-en commented
I found an issue with repositories not being applied at times, which I've fixed in the new Gradle structure at #112 
Which other problems did you have? I'll try and remedy them as soon as i can, sorry for not having been as thorough for testing too.

2024-12-31 03:29 UTC, BluSpring commented
There's an issue with launching the game itself, especially with Forge mods installed, where it would fail to properly apply the properties into the FMJ:

```log
[04:02:45] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.20.1 with Fabric Loader 0.16.9
[04:02:46] [ForkJoinPool-1-worker-2/WARN] (FabricLoader/Metadata) Mod not-that-cc uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[04:02:46] [main/WARN] (FabricLoader/Resolution) Mod resolution failed
[04:02:46] [main/INFO] (FabricLoader/Resolution) Immediate reason: [HARD_DEP_NO_CANDIDATE kilt 0.0.1+mc1.20.1+build.7e7cb9-local {depends fabricloader @ [>=valueof(GradlePropertyValueSource)]}, ROOT_FORCELOAD_SINGLE kilt 0.0.1+mc1.20.1+build.7e7cb9-local]
[04:02:46] [main/INFO] (FabricLoader/Resolution) Reason: [HARD_DEP kilt 0.0.1+mc1.20.1+build.7e7cb9-local {depends fabricloader @ [>=valueof(GradlePropertyValueSource)]}, HARD_DEP kilt 0.0.1+mc1.20.1+build.7e7cb9-local {depends fabric-api @ [>=valueof(GradlePropertyValueSource)]}, HARD_DEP kilt 0.0.1+mc1.20.1+build.7e7cb9-local {depends minecraft @ [valueof(GradlePropertyValueSource)]}, HARD_DEP kilt 0.0.1+mc1.20.1+build.7e7cb9-local {depends fabric-language-kotlin @ [>=valueof(GradlePropertyValueSource)]}, HARD_DEP kilt 0.0.1+mc1.20.1+build.7e7cb9-local {depends mm @ [>=valueof(GradlePropertyValueSource)]}, HARD_DEP kilt 0.0.1+mc1.20.1+build.7e7cb9-local {depends forgeconfigapiport @ [>=valueof(GradlePropertyValueSource)]}, HARD_DEP kilt 0.0.1+mc1.20.1+build.7e7cb9-local {depends architectury @ [>=valueof(GradlePropertyValueSource)]}]
[04:02:46] [main/INFO] (FabricLoader/Resolution) Fix: add [], remove [], replace [[kilt 0.0.1+mc1.20.1+build.7e7cb9-local] -> add:kilt 1 ([(-∞,∞)])]
[04:02:46] [main/ERROR] (FabricLoader) Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Kilt' (kilt) 0.0.1+mc1.20.1+build.7e7cb9-local with any version that is compatible with:
		 - fabricloader 0.16.9
		 - fabric-api 0.92.2+1.20.1
		 - minecraft 1.20.1
		 - fabric-language-kotlin 1.13.0+kotlin.2.1.0
		 - mm 2.3
		 - forgeconfigapiport 8.0.1
		 - architectury 9.2.14
More details:
	 - Mod 'Kilt' (kilt) 0.0.1+mc1.20.1+build.7e7cb9-local requires version valueof(GradlePropertyValueSource) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.16.9!
	 - Mod 'Kilt' (kilt) 0.0.1+mc1.20.1+build.7e7cb9-local requires version valueof(GradlePropertyValueSource) of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.92.2+1.20.1!
	 - Mod 'Kilt' (kilt) 0.0.1+mc1.20.1+build.7e7cb9-local requires version valueof(GradlePropertyValueSource) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Kilt' (kilt) 0.0.1+mc1.20.1+build.7e7cb9-local requires version valueof(GradlePropertyValueSource) of mod 'Fabric Language Kotlin' (fabric-language-kotlin), but only the wrong version is present: 1.13.0+kotlin.2.1.0!
	 - Mod 'Kilt' (kilt) 0.0.1+mc1.20.1+build.7e7cb9-local requires version valueof(GradlePropertyValueSource) of mod 'Manningham Mills' (mm), but only the wrong version is present: 2.3!
	 - Mod 'Kilt' (kilt) 0.0.1+mc1.20.1+build.7e7cb9-local requires version valueof(GradlePropertyValueSource) of mod 'Forge Config API Port' (forgeconfigapiport), but only the wrong version is present: 8.0.1!
	 - Mod 'Kilt' (kilt) 0.0.1+mc1.20.1+build.7e7cb9-local requires version valueof(GradlePropertyValueSource) of mod 'Architectury' (architectury), but only the wrong version is present: 9.2.14!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[?:?]
```

Additionally, it seems like this PR somehow broke the DFU?
```log
[04:04:56] [main/ERROR] (FabricLoader) A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt' at 'xyz.bluspring.kilt.loader.KiltEarlyInitializer'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kilt' at 'xyz.bluspring.kilt.loader.KiltEarlyInitializer'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 3 more
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.Util.doFetchChoiceType(Util.java:242) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.Util.fetchChoiceType(Util.java:235) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.entity.EntityType$Builder.build(EntityType.java:763) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.entity.EntityType.register(EntityType.java:168) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:175) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.item.Items.<clinit>(Items.java:797) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.level.block.LightBlock.getShape(LightBlock.java:56) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.getShape(BlockBehaviour.java:1032) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.getShape(BlockBehaviour.java:1028) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour.getCollisionShape(BlockBehaviour.java:349) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase$Cache.<init>(BlockBehaviour.java:1293) ~[minecraft-merged-f0654d1df1-1.20.1-loom.mappings.1_20_1.layered+hash.1899487486-v2.jar:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.initCache(Blo [...]

2024-12-31 03:36 UTC, xtrm-en commented
The first issue seems relatively straightforward to fix, DFU on the other hand... what?

2024-12-31 03:37 UTC, BluSpring commented
My thoughts exactly.